<a href="https://colab.research.google.com/github/sahil1704/NumpyTl/blob/main/NumpyTl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

 Creating an array in numpy is to use Python list

In [5]:
myPythonList = [2,0,0,3]
print(myPythonList)

[2, 0, 0, 3]


To convert python list to a numpy array by using the object np.array.

In [6]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([2, 0, 0, 3])

In [8]:
a  = np.array([2,0,0,3])
print(a)

[2 0 0 3]


In [9]:
x=numpy_array_from_list + 10
print(x)

[12 10 10 13]


Shape of array

In [10]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [11]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [12]:
### 2 dimension
c = np.array([(1,2,3), 
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [13]:
### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

numpy.zeros() or np.zeros

In [14]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [15]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

Reshape Data

In [16]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

Flatten Data

In [17]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

hstack

In [18]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


vstack

In [19]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


Generate random numbers

In [20]:
## Generate random number from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)		

[4.07903054 6.02112621 5.10861061 4.18926126 5.8707775  4.79222153
 4.99545543 4.99171601 4.98716409 5.16706211]


Asarray

In [21]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


numpy.arange()

In [23]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

Linspace

In [25]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

LogSpace

In [27]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [28]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

Slicing Data

In [29]:
## Slice
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [30]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [31]:
print('Second column:', e[:,1])

Second column: [2 5]


In [32]:
## Second Row, two values
print(e[1, :2])

[4 5]


NumPy

Function Numpy Min np.min() Max np.max() Mean np.mean() Median np.median() Standard deviation np.std()

In [33]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.94734959 4.92375729 5.21818736 5.03501777 3.94469845 5.52261855
 3.46904724 4.45415097 4.73396505 5.11676768]


In [34]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

3.469047235678484
5.522618553148731
4.736555993654364
4.935553440750959
0.5896064685283439


Numpy.dot product

In [35]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

Matrix multipilcation

In [36]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

Inverse of a matrix using numpy

In [37]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


Determinant of a matrix using numpy

In [38]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


Rank of a Matrix

In [39]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

Calculate Eigenvectors And Eigenvalues With Numpy

In [40]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


Diagonal of a matrix

In [41]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


Matrix transpose

In [42]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


Trace of a matrix

In [43]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
